# version: 2.1

# jobs:
#   test:
#     docker:
#       - image: cimg/node:16.15.0
#     steps:
#       - checkout

#       # Install NPM version 8.5.5
#       - run:
#           name: Install npm 8.5.5
#           command: npm install -g npm@8.5.5

#       # Install Nightwatch version 8.5.5
#       - run:
#           name: Install Nightwatch 8.5.5
#           command: npm install -g nightwatch@latest
#       - run:
#           name: Install ChromeDriver
#           command: |
#             CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.chromium.org/downloads | grep -oP 'ChromeDriver \K[0-9.]+')
#             wget -qP /tmp https://chromedriver.chromium.org/downloads/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
#             unzip -q /tmp/chromedriver_linux64.zip -d /tmp
#             chmod +x /tmp/chromedriver
#             sudo mv /tmp/chromedriver ./chromedriver
#       - run:
#           name: Install nightwatch-axe-verbose
#           command: npm install nightwatch-axe-verbose --save-dev

#       # Run npm run test
#       - run:
#           name: Run Tests
#           command: npm run test

# workflows:
#   version: 2
#   test:
#     jobs:
#       - test
version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          command: npm run test
      - store_test_results:
          path: /tests_output

workflows:
  e2e-test:
    jobs:
      - test
