version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.15.0
    working_directory: ~/repo

    steps:
      - checkout

      # Restore dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install Firefox
          command: |
            sudo apt-get update
            sudo apt-get install -y firefox
      - run:
          name: Install GeckoDriver
          command: |
            if [ ! -f /usr/local/bin/geckodriver ]; then
              GECKODRIVER_VERSION=$(curl -sS https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
              curl -sS -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
              tar -xzf /tmp/geckodriver.tar.gz -C /tmp
              chmod +x /tmp/geckodriver
              sudo mv /tmp/geckodriver /usr/local/bin/geckodriver
            fi
      # Save dependencies for future runs
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Print Firefox version
          command: firefox --version

      - run:
          name: Install nightwatch-axe-verbose
          command: npm install nightwatch-axe-verbose --save-dev
      # Run Jest tests
      - run:
          name: Run nightwatch tests
          command: npm run test

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
