version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      # Install NVM and use Node.js version 16
      - run:
          name: Install Node.js with NVM
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 16
            nvm use 16

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run Nightwatch tests
      - run:
          name: Run Nightwatch Tests
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - test
