version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout

      - run:
          name: Update APT
          command: sudo apt-get update

      # Install NPM version 8.5.5
      - run:
          name: Install npm 8.5.5
          command: npm install -g npm@8.5.5

      # Install Nightwatch version 8.5.5
      - run:
          name: Install Nightwatch 8.5.5
          command: npm install -g nightwatch@latest

      - run:
          name: Install dependencies
          command: sudo apt-get install -y libnss3
      # Install ChromeDriver
      - run:
          name: Install ChromeDriver
          command: |
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            curl -sS -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip -q /tmp/chromedriver.zip -d /tmp
            chmod +x /tmp/chromedriver
            sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver

      # Print ChromeDriver version for debugging
      - run:
          name: Print ChromeDriver version
          command: chromedriver --version

      - run:
          name: Install nightwatch-axe-verbose
          command: npm install nightwatch-axe-verbose --save-dev

      # Run npm run test with verbose output
      - run:
          name: Run Tests
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
