version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.7

jobs:
  test:
    docker:
      - image: cimg/node:16.15.0
    working_directory: ~/repo

    steps:
      - checkout

      # Restore dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      # Install Node.js 16
      - run:
          name: Install Node.js
          command: nvm install 16.15.0 && nvm use 16.15.0

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Install Firefox and Geckodriver
          command: |
            browser-tools setup-firefox

      # Save dependencies for future runs
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Print Firefox version
          command: firefox --version

      - run:
          name: Install nightwatch-axe-verbose
          command: npm install nightwatch-axe-verbose --save-dev

      # Use expect to automate npm init nightwatch
      - run:
          name: Initialize Nightwatch
          command: |
            expect -c '
              spawn npm init nightwatch
              expect "\n\n\n"
              expect "\rtest"
              send "\r"
              interact
            '

      # Run Nightwatch tests
      - run:
          name: Run nightwatch tests
          command: npm run test

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
