version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout

      # Install NPM version 8.5.5
      - run:
          name: Install npm 8.5.5
          command: npm install -g npm@8.5.5

      # Install Nightwatch version 8.5.5
      - run:
          name: Install Nightwatch 8.5.5
          command: npm install -g nightwatch@latest

      # Install Chrome and ChromeDriver in user-specific directory
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            apt-get update && apt-get install -y wget unzip
            CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -qP /tmp https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip -q /tmp/chromedriver_linux64.zip -d /tmp
            chmod +x /tmp/chromedriver
            sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
            CHROME_PATH="/usr/local/bin/chrome"
            wget -qP /tmp https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            dpkg -x /tmp/google-chrome-stable_current_amd64.deb /tmp/chrome
            sudo mv /tmp/chrome/opt/google/chrome /opt/google/chrome
            echo "CHROME_PATH=$CHROME_PATH" > /etc/environment
            echo 'export PATH=$PATH:$CHROME_PATH' >> /etc/bash.bashrc

      # Install nightwatch-axe-verbose
      - run:
          name: Install nightwatch-axe-verbose
          command: npm install nightwatch-axe-verbose --save-dev

      # Run npm run test
      - run:
          name: Run Tests
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test
