version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout

      - run:
          name: Update APT
          command: sudo apt-get update

      # Install NPM version 8.5.5
      - run:
          name: Install npm 8.5.5
          command: npm install -g npm@8.5.5

      # Install Nightwatch version 8.5.5
      - run:
          name: Install Nightwatch 8.5.5
          command: npm install -g nightwatch@latest

      # Install Firefox and GeckoDriver
      - run:
          name: Install Firefox and GeckoDriver
          command: |
            sudo apt-get install -y firefox
            GECKODRIVER_VERSION=$(curl -sS https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r .tag_name)
            curl -sS -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
            tar -xzf /tmp/geckodriver.tar.gz -C /tmp || echo "Retrying tar extraction..." && sleep 1 && tar -xzf /tmp/geckodriver.tar.gz -C /tmp
            chmod +x /tmp/geckodriver
            sudo mv /tmp/geckodriver /usr/local/bin/geckodriver

      # Print GeckoDriver version for debugging
      - run:
          name: Print GeckoDriver version
          command: geckodriver --version

      - run:
          name: Install nightwatch-axe-verbose
          command: npm install nightwatch-axe-verbose --save-dev

      # Run npm run test with verbose output
      - run:
          name: Run Tests
          command: npm run test -- --verbose

workflows:
  version: 2
  test:
    jobs:
      - test
